### ISSUE TITLE
Wrong code repository name

### ISSUE THREAD

**Issue by raortegar** [blockademy/moodle-mod_pokcertificate#1]
Hello, 

According the Moodle documentation https://moodledev.io/general/community/plugincontribution/checklist#code-repository-name 
The repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin. The correct format to use is moodle-{plugintype}_{pluginname}.

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top.

Cheers.

**Comment by gonzalob** [comment]
Renamed as requested.

**Comment by raortegar** [comment]
Hello Gonzalo, 
The plugin type is not correct, in this link you can find more information about it https://moodledev.io/docs/4.5/apis/plugintypes See column Component name ([Frankenstyle](https://moodledev.io/general/development/policies/codingstyle/frankenstyle))

You can find your plugin type here https://github.com/blockademy/moodle-activity_pokcertificate/blob/development/version.php#L29

So in this case the name should be  moodle-mod_pokcertificate :)

**Comment by gonzalob** [comment]
Thanks for the links to the docs! That made it way clearer.

Fixed.
