### ISSUE TITLE
Hardcoded mdl_ prefix in classes/helper.php

### ISSUE THREAD

**Issue by mudrd8mz** [blockademy/moodle-mod_pokcertificate#3]
There are places with hard-coded `mdl_` prefix in your code. That doesn't work on Moodle installations with non-default prefix:

![image](https://github.com/user-attachments/assets/a78b9a16-402c-4598-b852-92b2b6fbabcb)

Please refer to https://moodledev.io/docs/4.5/apis/core/dml#table-prefix

**Comment by gonzalob** [comment]
Fixed on 75d0438a25d711ebeeaf32c7a1487189a4794df4
